##### 基本配置
server:
  port: 8502
spring:
  application:
    name: consumer
##### Consul配置
  cloud:
    consul:
      discovery:
        serviceName: consumer
        register: true
      #      host: http://10.10.0.248
      host: http://127.0.0.1
      port: 8500
##### feign配置
feign:
  hystrix:
    enabled: true
##### Zipkin 配置
  zipkin:
    base-url: http://localhost:8602
  sleuth:
    sampler:
      percentage: 1.0
##### actuator配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env
  endpoint:
    health:
      show-details: ALWAYS
##### 日志配置
logging:
  level:
    #    org.springframework.cloud.netflix.feign: debug
    org.springframework.cloud.openfeign: debug