##### 基本配置
server:
  port: 8501
spring:
  application:
    name: producer
##### Consul配置
  cloud:
    consul:
      discovery:
        serviceName: producer
        register: true
      #      host: http://10.10.0.248
      host: http://127.0.0.1
      port: 8500
##### Zipkin 配置
  zipkin:
    base-url: http://localhost:8602
  sleuth:
    sampler:
      percentage: 1.0
##### actuator配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env
  endpoint:
    health:
      show-details: ALWAYS